package main

import (
	"flag"
	"path"
	"path/filepath"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	var (
		isSimple      bool
		packageSuffix string
	)

	flagSet := flag.NewFlagSet("invoker", flag.ContinueOnError)
	flagSet.BoolVar(&isSimple, "simple", false, "Generate simple signatures without wrappers")
	flagSet.StringVar(&packageSuffix, "package_suffix", "connect", "Suffix for the generated sub-package")

	protogen.Options{
		ParamFunc: func(name, value string) error {
			switch name {
			case "simple":
				if value == "" {
					isSimple = true
				} else {
					isSimple = (value == "true")
				}
			case "package_suffix":
				packageSuffix = value
			}
			return nil
		},
	}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, file := range plugin.Files {
			if !file.Generate || len(file.Services) == 0 {
				continue
			}
			generateInvokerFile(plugin, file, isSimple, packageSuffix)
		}
		return nil
	})
}

func generateInvokerFile(gen *protogen.Plugin, file *protogen.File, isSimple bool, packageSuffix string) {
	goPackageName := file.GoPackageName
	goImportPath := file.GoImportPath

	if packageSuffix != "" {
		goPackageName += protogen.GoPackageName(packageSuffix)
		prefix := filepath.ToSlash(file.GeneratedFilenamePrefix)

		generatedFilenamePrefix := path.Join(
			path.Dir(prefix),
			string(goPackageName),
			path.Base(prefix),
		)

		goImportPath = protogen.GoImportPath(path.Join(
			string(file.GoImportPath),
			string(goPackageName),
		))

		file.GeneratedFilenamePrefix = generatedFilenamePrefix
	}

	filename := file.GeneratedFilenamePrefix + ".invoker.go"
	g := gen.NewGeneratedFile(filename, goImportPath)

	if packageSuffix != "" {
		g.Import(file.GoImportPath)
	}

	g.P("// Code generated by protoc-gen-connect-go-invoker. DO NOT EDIT.")
	g.P("//")
	g.P("// Source: ", file.Desc.Path())
	g.P()
	g.P("package ", goPackageName)
	g.P()

	ctxIdent := protogen.GoIdent{GoImportPath: "context", GoName: "Context"}
	fmtIdent := protogen.GoIdent{GoImportPath: "fmt", GoName: "Errorf"}
	protoIdent := protogen.GoIdent{GoImportPath: "google.golang.org/protobuf/proto", GoName: "Unmarshal"}
	connectIdent := protogen.GoIdent{GoImportPath: "connectrpc.com/connect", GoName: "NewRequest"}

	for _, service := range file.Services {
		serviceName := service.GoName
		structName := serviceName + "Invoker"
		handlerName := serviceName + "Handler"

		g.P("// ", structName, " wraps a ", handlerName, " to provide dynamic unary method invocation.")
		g.P("type ", structName, " struct {")
		g.P("	svc ", handlerName)
		g.P("}")
		g.P()

		g.P("// New", structName, " creates a new invoker for ", handlerName)
		g.P("func New", structName, "(svc ", handlerName, ") *", structName, " {")
		g.P("	return &", structName, "{svc: svc}")
		g.P("}")
		g.P()

		g.P("// Invoke calls the specified unary fully-qualified procedure using a raw binary protobuf payload.")
		g.P("func (i *", structName, ") Invoke(ctx ", g.QualifiedGoIdent(ctxIdent), ", procedure string, payload []byte) (any, error) {")
		g.P("	switch procedure {")

		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}

			g.P("	case ", service.GoName, method.GoName, "Procedure:")
			inputName := g.QualifiedGoIdent(method.Input.GoIdent)

			g.P("		req := &", inputName, "{}")
			g.P("		if err := ", g.QualifiedGoIdent(protoIdent), "(payload, req); err != nil { return nil, ", g.QualifiedGoIdent(fmtIdent), "(\"unmarshal: %w\", err) }")

			if isSimple {
				g.P("		return i.svc.", method.GoName, "(ctx, req)")
			} else {
				g.P("		res, err := i.svc.", method.GoName, "(ctx, ", g.QualifiedGoIdent(connectIdent), "(req))")
				g.P("		if err != nil { return nil, err }")
				g.P("		return res.Msg, nil")
			}
		}

		g.P("	default:")
		g.P("		return nil, ", g.QualifiedGoIdent(fmtIdent), "(\"unary procedure %s not found in ", serviceName, "\", procedure)")
		g.P("	}")
		g.P("}")
		g.P()
	}
}
