package main

import (
	"path"
	"path/filepath"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	var isSimple bool

	protogen.Options{
		ParamFunc: func(name, value string) error {
			if name == "simple" {
				isSimple = (value == "true" || value == "")
			}
			return nil
		},
	}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if !file.Generate || len(file.Services) == 0 {
				continue
			}
			generateDispatchFile(plugin, file, isSimple)
		}
		return nil
	})
}

func generateDispatchFile(gen *protogen.Plugin, file *protogen.File, isSimple bool) {
	packageSuffix := "connect"
	goPackageName := file.GoPackageName + protogen.GoPackageName(packageSuffix)

	prefix := filepath.ToSlash(file.GeneratedFilenamePrefix)
	generatedFilenamePrefix := path.Join(path.Dir(prefix), string(goPackageName), path.Base(prefix))
	filename := generatedFilenamePrefix + ".invoker.go"

	fakeImportPath := protogen.GoImportPath(string(file.GoImportPath) + packageSuffix)
	g := gen.NewGeneratedFile(filename, fakeImportPath)

	g.P("// Code generated by protoc-gen-connect-go-invoker. DO NOT EDIT.")
	g.P("package ", goPackageName)
	g.P()

	ctxIdent := protogen.GoIdent{GoImportPath: "context", GoName: "Context"}
	fmtIdent := protogen.GoIdent{GoImportPath: "fmt", GoName: "Errorf"}
	protoIdent := protogen.GoIdent{GoImportPath: "google.golang.org/protobuf/proto", GoName: "Unmarshal"}
	connectIdent := protogen.GoIdent{GoImportPath: "connectrpc.com/connect", GoName: "NewRequest"}

	for _, service := range file.Services {
		serviceName := service.GoName
		structName := serviceName + "Invoker"

		g.P("// ", structName, " wraps a ", serviceName, "Handler to provide dynamic unary method invocation.")
		g.P("type ", structName, " struct {")
		g.P("	svc ", serviceName, "Handler")
		g.P("}")
		g.P()

		g.P("func New", structName, "(svc ", serviceName, "Handler) *", structName, " {")
		g.P("	return &", structName, "{svc: svc}")
		g.P("}")
		g.P()

		g.P("// Invoke calls the specified unary method using a raw binary Protobuf payload.")
		g.P("func (i *", structName, ") Invoke(ctx ", g.QualifiedGoIdent(ctxIdent), ", method string, payload []byte) (any, error) {")
		g.P("	switch method {")

		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}

			g.P("	case \"", method.GoName, "\":")
			inputName := g.QualifiedGoIdent(method.Input.GoIdent)

			g.P("		req := &", inputName, "{}")
			g.P("		if err := ", g.QualifiedGoIdent(protoIdent), "(payload, req); err != nil { return nil, ", g.QualifiedGoIdent(fmtIdent), "(\"unmarshal: %w\", err) }")

			if isSimple {
				g.P("		return i.svc.", method.GoName, "(ctx, req)")
			} else {
				g.P("		res, err := i.svc.", method.GoName, "(ctx, ", g.QualifiedGoIdent(connectIdent), "(req))")
				g.P("		if err != nil { return nil, err }")
				g.P("		return res.Msg, nil")
			}
		}

		g.P("	default:")
		g.P("		return nil, ", g.QualifiedGoIdent(fmtIdent), "(\"method %s not found in ", serviceName, "\", method)")
		g.P("	}")
		g.P("}")
		g.P()
	}
}
